### ISSUE TITLE
Error output stack trace could be more useful

### ISSUE THREAD

**Issue by nathanmarks** [spion/blue-tape#21]
**Note:** I don't know enough about Bluebird's handling of stack traces to know if what I'm bringing up is unique to my setup or a common problem.

Currently my error output looks like this:

```
✖ TypeError: Cannot read property 'jobId' of undefined
    -------------------------------------------------------
      operator: error
      expected: |-
        undefined
      actual: |-
        [TypeError: Cannot read property 'jobId' of undefined]
      at: tryCatcher (/d/node_modules/bluebird/js/release/util.js:16:23)
      stack: |-
```

Unfortunately, the error stack trace line there isn't very helpful for me.

```
  [TypeError: Cannot read property 'jobId' of undefined]
      at: tryCatcher (/d/node_modules/bluebird/js/release/util.js:16:23)
```

But if I catch the error myself at the end of the test and `console.log(err.stack)`, the start of my output looks like this:

```
    TypeError: Cannot read property 'jobId' of undefined
        at waitForJobToFinish (mozQueue.js:59:49)
        at mozQueue.js:49:40
```

Which is exactly where the error is.

**Comment by spion** [comment]
I can't tel for sure without looking at the example code, but can you try setting the env variable `BLUEBIRD_DEBUG=1` and see if that makes a difference?

**Comment by nathanmarks** [comment]
@spion Same thing with the env var set. Here's some example code:

Test:
```js
Test('MozQueue Integration', t => {
  // test setup

  return MozQueue.addUrls(urls)
    .then(jobs => Promise.all(map(n => waitForJobToFinish(n), jobs)))
    .then(result =>  t.deepEquals(result, expected, 'should have the correct output'));
});
```

If I remove the arg `n` from the `waitForJobToFinish()` call, I encounter the scenario outlined in the original post.

Here is the `waitForJobToFinish()` function. You can see where it fails if the arg is not provided (tries to access the property `job.jobId`, assuming it is an object and not undefined);

```
export function waitForJobToFinish (job) {
  const jobId = typeof job === 'number' ? job : job.jobId;

  return jobTracker.waitForJobToFinish(jobId);
}
```

**Comment by nathanmarks** [comment]
Would you rather I try reproduce this in a test and submit a PR?

**Comment by spion** [comment]
@nathanmarks A standalone test-case would be lovely, a PR even nicer

**Comment by spion** [comment]
The solution would be to send the captured exception to tape. Tape assumes that the error was caused in a sync context and generates a new Error object, capturing its trace. However because the function has already returned this trace is useless.

The patch would modify Test.prototype.assert to use the passed error object instead of generating a new one: https://github.com/substack/tape/blob/40be68520fedee580462bfaa7e91651154a65bea/lib/test.js#L212

**Comment by nathanmarks** [comment]
The stack is empty for me, I just get the `at:` line:

```
stack: |-
```

**Comment by spion** [comment]
With a similar example (and `BLUEBIRD_DEBUG=1`) I get:

```
    at: tryCatcher (blue-tape/node_modules/bluebird/js/release/util.js:16:23)
    stack: |-
      TypeError: Cannot read property 'map' of undefined
          at blue-tape/test.js:13:35
      From previous event:
          at Test.<anonymous> (blue-tape/test.js:13:4)
          [...snip...]
```

example:

```js
var t = require('./blue-tape');
var P = require('bluebird');


function fail(x) {
  return x.foo();
}

var items = [1,2,3]

t.test("stack", function() {
  return P.resolve()
  .then(items => Promise.all(items.map(i => fail(i))));
});
```

Might need a test case to reproduce that issue then (the stack missing)

**Comment by nathanmarks** [comment]
@spion Ok, let me see what I can pull together for you

**Comment by nathanmarks** [comment]
@spion 

Had inexplicable issues putting together a **simple** example.

I'm not sure if this helps, but I did dig into `tape` and follow the trail. You're correct, in `Test.prototype.error` I can still access my stack trace. in `Test.prototype._assert()` it is lost.

Is this because I'm executing my tests with `babel-node`?

**Comment by spion** [comment]
@nathanmarks I doubt it, I get the same stack trace with `babel-node`.

The issue with `Test.prototype._assert()` only pertains to the `at:' line. The `stack` line is different:

[https://github.com/substack/tape/blob/master/lib/results.js#L156-L165](https://github.com/substack/tape/blob/40be68520fedee580462bfaa7e91651154a65bea/lib/results.js#L156-L165)

and is taken from the actual error.

**Comment by nathanmarks** [comment]
@spion You're going to hate me. I was piping my output all this time into https://github.com/scottcorgan/tap-spec

and I **think** this is causing the issue: (from `tap-out`) https://github.com/scottcorgan/tap-out/blob/master/lib/assert.js#L18

**Comment by nathanmarks** [comment]
The raw output from `tap-out` is missing the stack trace which **is** present in the raw tap output:

```
"raw": "    operator: error\n    expected: |-\n      undefined\n    actual: |-\n      [TypeError: Cannot read property 'system' of undefined]\n    at: run (/Users/PoweredbySearch/Development/repos/poweredbysearch/vioc-dashboard-tools/node_modules/core-js/modules/es6.promise.js:104:47)\n    stack: |-"
```

**Comment by spion** [comment]
Ha! So is tap-spec doing that to all `tape` stack traces, or just blue-tape?

**Comment by spion** [comment]
Any news?

**Comment by nathanmarks** [comment]
@spion So many things to debug, too little time... It's on my radar!

**Comment by raphinesse** [comment]
@spion This only happens to the `blue-tape` stack traces, `tape` stack traces are passed through untouched.

I compared the raw tap output of both tools. After a common prefix, `blue-tape` prints the following to stdout
```
not ok 1 TypeError: Cannot read property 'paths' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'paths' of undefined]
    at: Test.run <REST OF LINE OMITTED>
    stack: |-
      TypeError: Cannot read property 'paths' of undefined
          at <MULTIPLE LINES OMITTED>
  ...

1..1
# tests 1
# pass  0
# fail  1
```
while `tape` prints nothing to stdout and this to stderr:
```
<PATH TO FILE>:32
  const paths = foo.bar.paths
                        ^

TypeError: Cannot read property 'paths' of undefined
    at <MULTIPLE LINES OMITTED>
```
which seems to be passed through untouched by `tap-spec`.

The test were run directly with `node`. No test runners or such.
